routes/web.php
<?php
use Illuminate\Support\Facades\Notification;
use App\Notifications\TripsheetSubmitted;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','TripController@home');

Route::get('/test', function(){
    // if(env('NOTIFICATIONS_ENABLED') == true){
        $tripsheet = new \App\TripSheet();
        $user = new \App\User();
        $user->email = 'murizwan11@gmail.com';
        Notification::send($user, new TripsheetSubmitted($tripsheet));
    // }
});

Auth::routes();

Route::get('/home', 'TripController@home')->name('home');
Route::post('save_calculations', 'EstimateController@store')->name('save');
Route::post('submit_tripsheet', 'TripController@submitTripsheet');
Route::post('update_tripsheet/{id}', 'TripController@updateTripsheet');

Route::resource('estimate', 'EstimateController');
Route::resource('trip', 'TripController');
Route::get('tripsheets/{filter?}', 'TripController@history')->name('tripsheet.history');

Route::get('download_csv/{filter?}', 'TripController@download_csv_file');


Route::get('tripsheet/{id}/status/{status}', 'TripController@setTripsheetStatus');

Route::post('tripsheet/status/update', 'TripController@updateTripsheetStatus')->name('update.tripsheet');
Route::post('tripsheet/status/bulk_update', 'TripController@updateTripsheetBulkStatus')->name('bulk.update.tripsheet');
Route::post('tripsheet/payment/update', 'TripController@updateTripsheetPaymentStatus')->name('update.tripsheet.payment');
Route::post('tripsheet/uploadcvs', 'TripController@uploadCVSFile')->name('tripsheet.upload');
Route::post('tripsheet/comparecvs', 'TripController@CompareCVSFile')->name('tripsheet.compare');
Route::post('tripsheet/adminnoteupdate', 'TripController@adminNoteUpdate')->name('tripsheet.adminnoteupdate');
Route::get('tripsheet/adjustdatabase', 'TripController@adjustDatabase')->name('tripsheet.adjust');
//Route::get('tripsheet/{filter}', 'TripController@history');
Route::delete('tripsheet/{id}', 'TripController@destroyTripsheet');


Route::resource('user', 'UserController');

Route::get('settings', 'UserController@getSettings');
Route::post('settings', 'UserController@postSettings');

Route::get('locale/{locale}', 'UserController@setLocale');

// Route::get('monthly_driver_summary', function(){

// })

app/Estimate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Estimate extends Model
{
    protected $fillable = [
        'customer_name',
        'customer_address',
        'customer_city',
        'customer_state',
        'customer_zip',
        'calculations_object',
        'created_by',
        'updated_by',
    ];

    public function creator()
    {
        return $this->belongsTo('App\User', 'created_by');
    }
    
    // public function getCalculationsAttribute(){
    //     return json_decode($this->calculations_object);
    // }

    public function updator()
    {
        return $this->belongsTo('App\User', 'updated_by');
    }
}

app/Http/Controllers/EstimateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Estimate;
use Illuminate\Support\Facades\Auth;


class EstimateController extends Controller
{
    
    public function __construct()
    {
        $this->middleware(['auth', 'locale']);
    }
    
    public function welcome(){
        return view('welcome');
    }

    public function index()
    {
        if(Auth::user()->role!='admin'){
            $estimates = Estimate::where('created_by', Auth::id())->orderBy('created_at', 'desc')->paginate(50);
        }else{
            $estimates = Estimate::orderBy('created_at', 'desc')->paginate(50);
        }
        return view('estimate.index', compact('estimates'));
    }
    
    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        // return $request->all();
        $estimate = new Estimate();
        $estimate->fill($request->all());
        $estimate->created_by = Auth::id();
        $estimate->save();
        $request->session()->flash('status', 'Estimate saved successfully!');
        return $this->index();
    }

    public function show($id)
    {
    }
    
    public function edit($id)
    {
        $estimate = Estimate::find($id);
        return view('estimate.edit', compact(['id']));
    }
    
    public function update(Request $request, $id)
    {
        $estimate =  Estimate::find($id);
        $estimate->fill($request->all());
        $estimate->updated_by = Auth::id();
        $estimate->save();
        $request->session()->flash('status', 'Updated successfully!');
        return redirect()->back();
    }

    public function destroy(Request $request, $id)
    {
        $estimate = Estimate::find($id);

        if (Auth::user()->role != 'admin' && Auth::id()!=$estimate->created_by  ) {
            return redirect()->back()->withErrors(['error' => 'You are not authorized to delete this estimate']);
        }

        Estimate::destroy($id);
        $request->session()->flash('status', 'Estimate deleted successfully!');
        return redirect()->back();

    }
}

resources/views/estimate/edit.blade.php
@extends('layouts.app')

@section('content')



 <form  action="{{route('estimate.update', $id)}}" method="POST" role="form">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="PUT">

    <section id="app" class="calc-table">


        <div class="container-fluid">
            
            <div class="text-center">
            <h2 class="text-warning">Saved Deal # {{$id}}</h2>
            </div>
           
            <deal-calculator show_download_button="true" url="{{url('api/estimate/'.$id)}}"></deal-calculator>
            
           
            
        </div>
        
        
        <nav class="navbar fixed-bottom navbar-light bg-light"> 
            <a href="{{url('/estimate')}}" class="btn btn-secondary btn-outline-secondary float-right">Cancel</a>

            @if (session('status'))
                <div class="alert alert-success mb-0">
                    {{ session('status') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger mb-0">
                    {{$errors->first()}}
                </div>
            @endif
            <button class="btn btn-warning" type="submit">Update</button>
  
        </nav>

    </section>
     </form>


@endsection

@section('scripts')
@endsection

resources/views/estimate/index.blade.php
@extends('layouts.app')

@section('content')

            <div class="card border-primary">
                <div class="card-body">
                     <legend class="text-primary">Estimates</legend>

                   

               <div class="table-responsive">

                   <table style="margin-top:40px;" class="table table-hover table-sm">
                       <thead>
                           <tr>
                               <th style="width:80px;">ID</th>
                               <th>Created At</th>
                               <th style="width:180px;">Action</th>
                            </tr>
                            
                        </thead>
                        
                        <tbody>
                            @foreach($estimates as $row)
                            <tr>
                                <td>{{$row->id}}</td>
                            
                                <td>
                                    {{$row->created_at}} <span class="badge badge-pill badge-light"  data-toggle="tooltip" title="{{$row->created_at}}">{{$row->created_at->diffForHumans()}}</span>
                                    @if($row->creator)by <span class="badge badge-pill badge-light">{{$row->creator->name}}</span>@endif
                                </td>
                                <td>

                                    <a href="{{route('estimate.edit', $row->id)}}" class="btn btn-sm btn-outline-warning">View</a>
                                <form class="form-delete" method="post" action="{{route('estimate.destroy', $row->id)}}">
                                        @csrf
                                        {{method_field('DELETE')}}
                                        <button type="submit" class="btn btn-sm btn-outline-danger btn-delete">Delete</button>
                                    </form>
                                    
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                    {{$estimates->links()}}
                </div>
                
            </div>
            
            @endsection
            
            @section('scripts')
            <script type="text/javascript">
$(function(){
    $('.preview').on('click', function(){
        // $('#preview-modal .modal-content').html('<preview-component url="{{url('api/estimate')}}/'+$(this).data('id')+'"></preview-component>');
        $('#preview-modal .modal-content').find('preview-component').attr('url', "{{url('api/estimate')}}/"+$(this).data('id'))
        $('#printable').data('name', $(this).data('name'));
        $('#preview-modal').modal();
    });
    
    
    
    $('#export-pdf').on('click', function(){
        var doc = new jsPDF();
         doc.fromHTML($('#printable').html(), 15, 15, {
            'width': 170
            // 'elementHandlers': specialElementHandlers
            });
            // doc.setFont('Arial');
            var name = $('#printable').data('name');
        doc.save(name+'.pdf');
        doc = null;
    });


    $('#export-docx').on('click', function(){
        var converted = htmlDocx.asBlob($('#printable').html());
            var name = $('#printable').data('name');
        saveAs(converted, name+'.docx');
    });
});
</script>
@endsection