routes/web.php
<?php
use Illuminate\Support\Facades\Notification;
use App\Notifications\TripsheetSubmitted;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','TripController@home');

Route::get('/test', function(){
    // if(env('NOTIFICATIONS_ENABLED') == true){
        $tripsheet = new \App\TripSheet();
        $user = new \App\User();
        $user->email = 'murizwan11@gmail.com';
        Notification::send($user, new TripsheetSubmitted($tripsheet));
    // }
});

Auth::routes();

Route::get('/home', 'TripController@home')->name('home');
Route::post('save_calculations', 'EstimateController@store')->name('save');
Route::post('submit_tripsheet', 'TripController@submitTripsheet');
Route::post('update_tripsheet/{id}', 'TripController@updateTripsheet');

Route::resource('estimate', 'EstimateController');
Route::resource('trip', 'TripController');
Route::get('tripsheets/{filter?}', 'TripController@history')->name('tripsheet.history');

Route::get('download_csv/{filter?}', 'TripController@download_csv_file');


Route::get('tripsheet/{id}/status/{status}', 'TripController@setTripsheetStatus');

Route::post('tripsheet/status/update', 'TripController@updateTripsheetStatus')->name('update.tripsheet');
Route::post('tripsheet/status/bulk_update', 'TripController@updateTripsheetBulkStatus')->name('bulk.update.tripsheet');
Route::post('tripsheet/payment/update', 'TripController@updateTripsheetPaymentStatus')->name('update.tripsheet.payment');
Route::post('tripsheet/uploadcvs', 'TripController@uploadCVSFile')->name('tripsheet.upload');
Route::post('tripsheet/comparecvs', 'TripController@CompareCVSFile')->name('tripsheet.compare');
Route::post('tripsheet/adminnoteupdate', 'TripController@adminNoteUpdate')->name('tripsheet.adminnoteupdate');
Route::get('tripsheet/adjustdatabase', 'TripController@adjustDatabase')->name('tripsheet.adjust');
//Route::get('tripsheet/{filter}', 'TripController@history');
Route::delete('tripsheet/{id}', 'TripController@destroyTripsheet');


Route::resource('user', 'UserController');

Route::get('settings', 'UserController@getSettings');
Route::post('settings', 'UserController@postSettings');

Route::get('locale/{locale}', 'UserController@setLocale');

// Route::get('monthly_driver_summary', function(){

// })

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'hourly_rate', 'locale', 'currency'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Akaunting\Setting;
class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function setLocale( $locale){
        $user = Auth::user();
        $user->locale = $locale;
        $user->save();
        return redirect()->back();
    }


    public function getSettings(Request $request){
        if( in_array($request->currency, ['EUR', 'USD', 'GBP'] ) ){
           $user = User::find(Auth::id());
           $user->currency = $request->currency;
           $user->save();
           return redirect()->back();

        }
        return view('user.settings');
    }

    public function postSettings(Request $request){
        $request->validate([
            'USD' => 'required|numeric',
            'GBP' => 'required|numeric',
        ]);

        \Setting::set('USD', $request->USD);
        \Setting::set('GBP', $request->GBP);
        \Setting::save();
    
        $request->session()->flash('status', 'Settings saved successfully!');
        return redirect()->back();
    }

    private function _getUsers(){
        if(Auth::user()->role == 'user'){
            return  [User::find(Auth::id())];
        }
        
        
        return User::all();
       
        
    }
   
    public function index()
    {
        if(Auth::user()->role == 'user'){
           return redirect(action('UserController@edit', Auth::id()));
        }

        $users = $this->_getUsers();
        return view('user.index', compact('users'));
    }

    public function create()
    {
        //
    }

   
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
            'role' => 'required|in:admin,user,super_admin',
            // 'hourly_rate' => 'required|numeric',
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'role' => $request->role,
            'hourly_rate' => 0,
            'password' => Hash::make($request->password),
        ]);

        $request->session()->flash('status', 'User created successfully!');
        return redirect()->back();

    }

   
    public function show($id)
    {
        //
    }

   
    public function edit($id)
    {
        $user = User::find($id);
        $users = $this->_getUsers();
        return view('user.index', compact('users', 'user'));
    }

    public function update(Request $request, $id)
    {
       $request->validate([
           'name' => 'required|string|max:255',
           'email' => 'required|string|email|max:255|unique:users,email,'.$id,
           'role' => 'required|in:admin,user,super_admin',
           'password' => 'nullable|string|min:6|confirmed',
        //    'hourly_rate' => 'required|numeric',
       ]);

       $user = User::find($id);
       $user->name = $request->name;

       $user->email = $request->email;

       $user->role = $request->role;
       $user->hourly_rate = 0;

       if(!empty($request->password)){
            $user->password = Hash::make($request->password);
        }

        $user->save();
        $request->session()->flash('status', 'User updated successfully!');
        return redirect()->back();
    }

    
    public function destroy($id, Request $request)
    {
        if(Auth::user()->role != 'admin' && Auth::user()->role != 'super_admin'){
            return redirect()->back()->withErrors(['error'=> 'Only admin can delete a user']);
        }

        if(Auth::id() == $id){
            return redirect()->back()->withErrors(['error'=> 'You can not delete your own account']);
        }
        
        if(User::count() == 1){
            return redirect()->back()->withErrors(['error'=> 'You are the only user left, so cannot be deleted']);
        }

        User::destroy($id);
        $request->session()->flash('status', 'User deleted successfully!');
        return redirect()->back();
    }
}

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')

            <div class="card @if(isset($user)) border-warning @else border-primary @endif">
                <!-- <div class="card-header">users</div> -->

                <div class="card-body">
                 
                    @if(isset($user))

                <form action="{{route('user.update', $user->id)}}" method="POST" role="form">
                    @if($user->role =='admin' || $user->role =='super_admin')
                        <legend class="text-warning">Edit user</legend>
                        @else
                        <legend class="text-warning">Edit Profile</legend>
                        @endif
                        <input type="hidden" name="_method" value="PUT">
                        @csrf
                         <div class="form-row">
                            
                        <div class="form-group col">
                            <label for="">Name</label>
                            <input type="text" autofocus  name="name" value="{{old('name', $user->name)}}" class="form-control" >
                        </div>
                        
                        <div class="form-group col">
                            <label for="">Email</label>
                            <input type="email"   name="email" value="{{old('email', $user->email)}}" class="form-control" >
                        </div> 
                        {{-- <div class="form-group col">
                            <label for="">Hourly Rate</label>
                            <input type="number" step="0.1"  required  name="hourly_rate" value="{{old('hourly_rate', $user->hourly_rate)}}" class="form-control" >
                        </div>  --}}
                        </div>
                        <div class="form-row">
                            
                        <div class="form-group col">
                            <label>Role</label>
                            <select name="role" class="form-control" required="required">
                                @if(Auth::user()->role == 'admin')  
                                    <option @if(old('role', $user->role) == 'admin') selected @endif value="admin">Admin</option>
                                @elseif(Auth::user()->role == 'super_admin') 
                                    <option @if(old('role', $user->role) == 'admin') selected @endif value="admin">Admin</option>
                                    <option @if(old('role', $user->role) == 'super_admin') selected @endif value="super_admin">Super Admin</option>
                                @endif
                                <option @if(old('role', $user->role) == 'user') selected @endif value="user">User</option>
                            </select>
                        </div>

                          <div class="form-group col">
                            <label for="">Password</label>
                            <input type="password"   name="password" class="form-control is-invalid" >
                        </div> 
                          <div class="form-group col">
                            <label for="">Confirm Password</label>
                            <input type="password"   name="password_confirmation" class="form-control is-invalid" >
                        </div> 
                        </div>
                        <div class="alert alert-warning" role="alert">Enter password only if you want to change it </div>
                        <button type="submit" class="btn btn-warning">Save</button>
                    <a href="{{url('user')}}" class="btn btn-secondary">Cancel</a>
                    </form>
                    
                    @else

                    
                    <form action="{{url('user')}}" method="POST" role="form">
                        <legend class="text-primary">Add User</legend>
                        @csrf
                        <div class="form-row">
                            
                        <div class="form-group col">
                            <label for="">Name</label>
                            <input type="text" autofocus  name="name" value="{{old('name')}}" class="form-control" >
                        </div>
                        
                        <div class="form-group col">
                            <label for="">Email</label>
                            <input type="email"   name="email" value="{{old('email')}}" class="form-control" >
                        </div> 

                          {{-- <div class="form-group col">
                            <label for="">Hourly Rate</label>
                            <input type="number" step="0.1"  required  name="hourly_rate" value="{{old('hourly_rate')}}" class="form-control" >
                        </div>  --}}
                        </div>
                        <div class="form-row">
                            
                        <div class="form-group col">
                            <label>Role</label>
                            <select  name="role" class="form-control" required="required">
                                <option @if(old('role') == 'admin') selected @endif value="admin">Admin</option>
                                <option @if(old('role') == 'user') selected @endif value="user">User</option>
                                
                                @if(Auth::user()->role == 'super_admin')
                                <option @if(old('role') == 'super_admin') selected @endif value="super_admin">Super Admin</option>
                                @endif
                                
                            </select>
                        </div>

                          <div class="form-group col">
                            <label for="">Password</label>
                            <input type="password"   name="password" class="form-control" >
                        </div> 
                          <div class="form-group col">
                            <label for="">Confirm Password</label>
                            <input type="password"   name="password_confirmation" class="form-control" >
                        </div> 
                        </div>

                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>

                    @endif
                    
                   
                    
               @if(Auth::user()->role == 'admin' || Auth::user()->role == 'super_admin')
                <table style="margin-top:40px;" class="table table-hover table-sm">
                    <thead>
                        <tr>
                            <th style="width:80px;">#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th style="width:250px;">Action</th>
                        </tr>

                    </thead>
                        <tbody>
                            <?php $i=1; ?>
                        @foreach($users as $user)
                            @if(Auth::user()->role == 'admin' && $user->role == 'super_admin')
                            
                            @else
                            <tr>
                                <td>{{$i++}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{$user->role}}</td>
                                <td>
                                <a href="{{route('user.edit', $user->id)}}" class="btn btn-sm btn-outline-warning">Edit</a>
                                <form class="form-delete" method="post" action="{{route('user.destroy', $user->id)}}">
                                    @csrf
                                    {{method_field('DELETE')}}
                                    <button type="submit" class="btn btn-sm btn-outline-danger btn-delete">Delete</button>
                                </form>
                                </td>
                            </tr>
                            @endif
                        @endforeach
                        </tbody>
                    </table>
                    @endif
                    </div>
                    
            </div>

@endsection

resources/views/user/settings.blade.php
@extends('layouts.app')

@section('content')

            <div class="card border-primary">
                
                <div class="card-body">
                    <legend class="text-primary">Currency Settings</legend>
                    <div class="alert alert-default bg-light" role="alert">
                        <strong>  Euro is the base currency</strong>
                    </div>
                    <form method="post" action="{{url('settings')}}">
                    {{csrf_field()}}
                    <div class="form-group">
                      <label for="">Dollar (USD)</label>
                      <input name="USD" value="{{\Setting::get('USD', '')}}" type="number" step="0.001" class="form-control"  placeholder="how many USD in 1 EUR">
                    </div>
               
                    <div class="form-group">
                      <label for="">Sterling (GBP)</label>
                      <input name="GBP" value="{{\Setting::get('GBP', '')}}" type="number" step="0.001" class="form-control"  placeholder="how many GBP in 1 EUR">
                    </div>

                    <button type="submit" class="btn btn-primary">
                        Save
                    </button>

                    </form>
                  
               
                </div>
            </div>
   
@endsection